server:
  port: 7003

eureka:
#  禁用Eureka的自我保护模式，实际环境不建议使用
#  server:
#    enable-self-preservation: false
  instance:
    hostname: eureka7001.com   #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。(eurekaServer不需要自己注册自己)
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:              # Eureka对外暴露的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
#      集群配置
#      注意在hosts文件里面加上如下配置(域名映射)
#      127.0.0.1  eureka7001.com
#      127.0.0.1  eureka7002.com
#      127.0.0.1  eureka7003.com
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/



